config/routes.rb
Rails.application.routes.draw do
  resources :meals

  root 'home#top'
  get '/about' => 'home#about'
end

app/models/meal.rb
class Meal < ActiveRecord::Base
  validates :title, presence: true
  validates :content, presence: true, length: { maximum: 200 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
    @message = "食事日記へようこそ"
  end

  def about

  end
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  before_action :set_meal, only: [:show, :edit, :update, :destroy]

  def new
    @meal = Meal.new
  end

  def create
    @meal = Meal.new(meal_params)
    if @meal.save
      redirect_to @meal, notice: '投稿が保存されました'
    else
      render :new
    end
  end

  def index
    @meals = Meal.all
  end

  def show
  end

  def edit
  end

  def update
    if @meal.update(meal_params)
      redirect_to @meal, notice: '投稿が更新されました'
    else
      render :edit
    end
  end

  def destroy
    @meal.destroy
    redirect_to meals_path
  end

  private
    def set_meal
      @meal = Meal.find(params[:id])
    end

    def meal_params
      params.require(:meal).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/views/home/about.html.erb
<h1>食事日記とは？</h1>
<p>食事日記はその日食べたものを写真とともに記録できるサービスです。<br>
日々の食事内容を投稿することで、自らの食習慣を見直すことができます。</p>

app/views/home/top.html.erb
<h1><%= @message %></h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>食事日記</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header class="navbar">
    <div class="container">
      <div id="logo">食事日記</div>
      <ul class="header-right">
        <li><%= link_to "トップページ", root_path %></li>
        <li><%= link_to "サイト概要", about_path %></li>
        <li><%= link_to "新規投稿する", new_meal_path%></li>
        <li><%= link_to "投稿一覧", meals_path%></li>
      </ul>
    </div>
  </header>

  <div class="container">
    <%= yield %>
  </div>

  <div class="container">
    <footer class="footer">
      <div class="small">
        &copy; 2017 Terunori Hashizume
      </div>
    </footer>
  </div>

</body>
</html>

app/views/meals/_form.html.erb
<%= form_for(@meal) do |f| %>
  <% if @meal.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= @meal.errors.count %>件のエラーがあります。</h2>
      <ul>
        <% @meal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  タイトル
  <%= f.text_field :title, class: "form-control title-field" %>
  内容
  <%= f.text_area :content, class: "form-control content-field" %>
  <%= f.submit "保存する", class: "btn primary-btn" %>
<% end %>

app/views/meals/edit.html.erb
<h1>投稿を編集する</h1>
<%= render 'form' %>

app/views/meals/index.html.erb
<h1>投稿の一覧</h1>
<ul class="notes">
  <% @meals.each do |meal| %>
    <li>
      <p>タイトル</p>
      <span class="content">
        <%= link_to meal.title, meal_path(meal.id) %>
      </span>
    </li>
  <% end %>
</ul>

app/views/meals/new.html.erb
<h1>新規投稿する</h1>
<%= render 'form' %>

app/views/meals/show.html.erb
<p id="notice" class="alert alert-success">
  <%= notice %>
</p>

<h2>タイトル</h2>
<p><%= @meal.title %></p>
<h2>内容</h2>
<p><%= @meal.content %></p>
<%= link_to '編集する', edit_meal_path(@meal.id), class: 'btn edit-btn' %>
<%= link_to '削除する', meal_path(@meal.id), method: 'delete', class: 'btn destroy-btn', 'data-confirm' => '本当に削除しますか？' %>